export type VongaProduct = {
  id: string;
  name: string;
  category: string;
  price: number;
  image: string;
  description: string;
  details: string[];
  sizes: string[];
  colours: string[];
  featured?: boolean;
  style?: string;
  subStyle?: string;
};

export const vongaProducts: VongaProduct[] = [
  { id: "ivory-pleated-pocket-dress", featured: true, name: "Ivory Pleated Pocket Dress", category: "Occasionwear", price: 2600, image: "/vonga/images/products/ivory-pleated-pocket-dress.webp", description: "A draped ivory mini with a plunging pleated bodice and structured hip pockets.", details: ["Pleated V-neckline", "Structured hip pockets", "Made in Pretoria"], sizes: ["XS","S","M","L","XL"], colours: ["Ivory"] },
  { id: "sunset-bloom-kimono-set", featured: true, name: "Sunset Bloom Kimono Set", category: "Occasionwear", price: 4600, image: "/vonga/images/products/sunset-bloom-kimono-set.webp", description: "An oversized floral jacquard duster layered over a matching tailored set.", details: ["Jacquard floral duster", "Matching wide-leg trousers", "Statement sleeve"], sizes: ["XS","S","M","L","XL"], colours: ["Sunset Orange"] },
  { id: "scarlet-bloom-mermaid-skirt", featured: true, name: "Scarlet Bloom Mermaid Skirt", category: "Occasionwear", price: 3800, image: "/vonga/images/products/scarlet-bloom-mermaid-skirt.webp", description: "A velvet puff-sleeve bodice paired with a sculpted floral mermaid skirt.", details: ["Velvet puff sleeve", "Floral satin mermaid skirt", "Atelier finishing"], sizes: ["S","M","L","XL"], colours: ["Noir / Scarlet"] },
  { id: "midnight-cross-gown", featured: true, name: "Midnight Cross Gown", category: "Occasionwear", price: 4200, image: "/vonga/images/products/midnight-cross-gown.webp", description: "A cross-front cutout bodice flowing into a sculpted midnight mermaid gown.", details: ["Cross-front cutout bodice", "Sculpted mermaid silhouette", "Fully lined"], sizes: ["S","M","L","XL"], colours: ["Midnight Navy"] },
  { id: "scarlet-rose-shoulder-gown", name: "Scarlet Rose Shoulder Gown", category: "Occasionwear", price: 3950, image: "/vonga/images/products/scarlet-rose-shoulder-gown.webp", description: "A dramatic scarlet gown crowned with a sculpted 3D rose shoulder embellishment.", details: ["Hand-appliquéd 3D rose petals", "Sculpted shoulder statement", "Fitted bodice"], sizes: ["XS","S","M","L","XL"], colours: ["Scarlet"] },
  { id: "scarlet-command-suit", name: "Wine Colourblock Blazer Suit", category: "Tailoring", price: 4200, image: "/vonga/images/categories/corporate-style/corporate-style-burgundy-twotone.webp", description: "A colourblocked blazer suit in wine and blush, tailored for polished, unapologetic authority.", details: ["Colourblock panelling", "Sharp notch lapel", "Two-piece set"], sizes: ["XS","S","M","L","XL"], colours: ["Wine / Blush"], style: "corporate-style" },
  { id: "golden-jacquard-blouse-set", name: "Golden Jacquard Blouse Set", category: "Occasionwear", price: 3200, image: "/vonga/images/products/golden-jacquard-blouse-set.webp", description: "An oversized jacquard blouse with sculpted balloon sleeves, paired with a fluid wide-leg trouser.", details: ["Sculpted balloon sleeve", "Jacquard floral weave", "Wide-leg trouser"], sizes: ["XS","S","M","L","XL"], colours: ["Gold / Ivory"] },
  { id: "chartreuse-satin-ballgown", name: "Chartreuse Satin Ballgown", category: "Occasionwear", price: 4400, image: "/vonga/images/products/chartreuse-satin-ballgown.webp", description: "A strapless sweetheart ballgown in lustrous chartreuse satin with a full tea-length skirt.", details: ["Structured sweetheart bodice", "Belted waist", "Full tea-length skirt"], sizes: ["XS","S","M","L","XL"], colours: ["Chartreuse"] },
  { id: "ivory-plunge-bubble-mini", name: "Ivory Plunge Bubble Mini", category: "Dresses", price: 2850, image: "/vonga/images/products/ivory-plunge-bubble-mini.webp", description: "A sculpted cap-sleeve mini with a plunging neckline and a rounded bubble hem.", details: ["Plunging V-neckline", "Structured cap sleeve", "Bubble hem skirt"], sizes: ["XS","S","M","L"], colours: ["Ivory"] },
  { id: "charcoal-pinafore-blouse-dress", name: "Charcoal Pinafore Blouse Dress", category: "Dresses", price: 3050, image: "/vonga/images/products/charcoal-pinafore-blouse-dress.webp", description: "A charcoal pinafore dress layered over a black puff-sleeve blouse for sharp, editorial polish.", details: ["Pinafore silhouette", "Detachable puff-sleeve blouse", "Fitted waist"], sizes: ["XS","S","M","L","XL"], colours: ["Charcoal / Black"] },
  { id: "black-satin-jumpsuit-set", name: "Black Satin Jumpsuit Set", category: "Occasionwear", price: 3400, image: "/vonga/images/products/black-satin-jumpsuit-set.webp", description: "A sleek satin two-piece with a boat-neck top and tapered, pocketed trouser.", details: ["Boat neckline", "Tapered pocketed trouser", "Lustrous satin finish"], sizes: ["XS","S","M","L","XL"], colours: ["Black"], style: "jump-suits" },
  { id: "crimson-ruffle-mermaid-gown", name: "Crimson Ruffle Mermaid Gown", category: "Occasionwear", price: 5400, image: "/vonga/images/products/crimson-ruffle-mermaid-gown.webp", description: "An off-shoulder mermaid gown crowned with a ruffled organza neckline over a glittering sheer skirt.", details: ["Ruffled off-shoulder neckline", "Glitter mermaid silhouette", "Sheer godet skirt"], sizes: ["S","M","L","XL","2XL"], colours: ["Crimson"] },
  { id: "ivory-rose-crop-set", name: "Ivory Rose Crop Set", category: "Occasionwear", price: 3400, image: "/vonga/images/products/ivory-rose-crop-set.webp", description: "A cropped bustier finished with a sculpted satin rose, paired with a high-waisted tailored trouser.", details: ["Sculpted satin rose bustier", "Cropped silhouette", "High-waisted trouser"], sizes: ["XS","S","M","L","XL"], colours: ["Ivory"] },
  { id: "lilac-sequin-mermaid-gown", name: "Lilac Sequin Mermaid Gown", category: "Occasionwear", price: 5600, image: "/vonga/images/products/lilac-sequin-mermaid-gown.webp", description: "A sequinned mermaid gown in lilac with a folded off-shoulder wrap collar.", details: ["Folded off-shoulder collar", "All-over sequin embroidery", "Mermaid silhouette"], sizes: ["S","M","L","XL","2XL"], colours: ["Lilac"] },
  { id: "jacquard-robe-coat-set", name: "Jacquard Robe Coat Set", category: "Occasionwear", price: 4800, image: "/vonga/images/products/jacquard-robe-coat-set.webp", description: "An oversized jacquard robe coat in a painterly multicolour print, layered over a sleek tailored jumpsuit.", details: ["Oversized robe coat", "Painterly jacquard print", "Sleek matching jumpsuit"], sizes: ["S","M","L","XL","2XL"], colours: ["Multicolour / Emerald"] },

  // Vonga Chic Gems
  { id: "scarlet-peplum-mini-dress", name: "Scarlet Peplum Mini Dress", category: "Dresses", price: 3200, image: "/vonga/images/categories/chic-gems/looks/gems-01-scarlet-peplum.webp", description: "A sculpted scarlet satin mini finished with a structured peplum waist.", details: ["Structured peplum waist", "Cap sleeve", "Fitted silhouette"], sizes: ["XS","S","M","L","XL"], colours: ["Scarlet"], style: "chic-gems" },
  { id: "pearl-cutout-mini-dress", name: "Pearl Cutout Mini Dress", category: "Dresses", price: 3600, image: "/vonga/images/categories/chic-gems/looks/gems-02-pearl-cutout.webp", description: "A fully beaded ivory mini with a cutout bodice, lace sleeves and a sweeping train.", details: ["Hand-beaded pearl finish", "Cutout bodice", "Sweeping detachable train"], sizes: ["S","M","L","XL","2XL"], colours: ["Ivory"], style: "chic-gems" },
  { id: "champagne-cape-mini-dress", name: "Champagne Cape Mini Dress", category: "Dresses", price: 3400, image: "/vonga/images/categories/chic-gems/looks/gems-03-champagne-cape.webp", description: "A one-shoulder champagne mini with a sequined bodice and a sweeping cape sleeve.", details: ["One-shoulder cape sleeve", "Sequined bodice", "Bow waist detail"], sizes: ["XS","S","M","L"], colours: ["Champagne"], style: "chic-gems" },
  { id: "ivory-sequin-column-dress", name: "Ivory Sequin Column Dress", category: "Occasionwear", price: 3900, image: "/vonga/images/categories/chic-gems/looks/gems-04-ivory-sequin-coat.webp", description: "A structured ivory column dress with a sequined bodice, sculpted peplum and thigh-high slit.", details: ["Sequined structured bodice", "Sculpted peplum sleeve", "Thigh-high slit"], sizes: ["XS","S","M","L","XL"], colours: ["Ivory"], style: "chic-gems" },

  // Vonga Bridals
  { id: "sunburst-mesh-mermaid-bridal-gown", name: "Sunburst Mesh Mermaid Gown", category: "Bridal", price: 9200, image: "/vonga/images/products/sunburst-mesh-mermaid-bridal-gown.webp", description: "A sculpted mermaid gown with sunburst mesh panelling and a sweeping detachable train.", details: ["Sunburst mesh panelling", "Sculpted mermaid silhouette", "Detachable sweeping train"], sizes: ["XS","S","M","L","XL"], colours: ["Ivory"], style: "brides" },
  { id: "halter-bubble-train-bridal-gown", name: "Halter Bubble Train Gown", category: "Bridal", price: 7800, image: "/vonga/images/products/halter-bubble-train-bridal-gown.webp", description: "A clean halter-neck gown finished with a dramatic bubble-hem train for a modern bridal silhouette.", details: ["Halter neckline", "Fluid A-line skirt", "Bubble-hem train"], sizes: ["XS","S","M","L","XL"], colours: ["Ivory"], style: "brides" },
  { id: "floral-applique-mermaid-bridal-gown", name: "Floral Appliqué Mermaid Gown", category: "Bridal", price: 8600, image: "/vonga/images/products/floral-applique-mermaid-bridal-gown.webp", description: "A long-sleeve mock-neck mermaid gown with hand-appliquéd 3D florals cascading across one shoulder.", details: ["Long-sleeve mock neck", "Hand-appliquéd 3D florals", "Sculpted mermaid skirt"], sizes: ["S","M","L","XL"], colours: ["Ivory"], style: "brides" },
  { id: "pearl-lace-bow-back-bridal-mini", name: "Pearl Lace Bow-Back Mini", category: "Bridal", price: 6900, image: "/vonga/images/products/pearl-lace-bow-back-bridal-mini.webp", description: "A pearl-embellished lace mini with sheer sleeves and an oversized satin bow at the back.", details: ["All-over pearl embellishment", "Sheer lace sleeves", "Oversized satin back bow"], sizes: ["XS","S","M","L"], colours: ["Ivory"], style: "brides" },

  // Vonga Kimonos — Flora Kimonos (belted floral duster + co-ord)
  { id: "emerald-garden-kimono-robe", name: "Emerald Garden Kimono Robe", category: "Kimono", price: 3600, image: "/vonga/images/categories/kimonos/flora/flora-01-emerald.webp", description: "An emerald floral duster with balloon sleeves, sashed over a matching co-ord.", details: ["Oversized floral duster", "Balloon sleeve", "Matching sash belt"], sizes: ["S","M","L","XL","2XL"], colours: ["Emerald Green"], style: "kimonos", subStyle: "flora" },
  { id: "lilac-mist-kimono-robe", name: "Lilac Mist Kimono Robe", category: "Kimono", price: 3600, image: "/vonga/images/categories/kimonos/flora/flora-02-lilac.webp", description: "A soft floral duster in lilac tones with dramatic bubble sleeves and a tie waist.", details: ["Dramatic bubble sleeve", "Self-tie waist sash", "Fluid floral drape"], sizes: ["S","M","L","XL","2XL"], colours: ["Lilac"], style: "kimonos", subStyle: "flora" },
  { id: "ocean-bloom-kimono-robe", name: "Ocean Bloom Kimono Robe", category: "Kimono", price: 3800, image: "/vonga/images/categories/kimonos/flora/flora-03-ocean.webp", description: "A watercolour floral duster in ocean blues and greens, sashed at the waist.", details: ["Watercolour floral print", "Balloon sleeve", "Emerald sash belt"], sizes: ["S","M","L","XL","2XL"], colours: ["Ocean Blue/Green"], style: "kimonos", subStyle: "flora" },
  { id: "blush-bloom-kimono-robe", name: "Blush Bloom Kimono Robe", category: "Kimono", price: 3600, image: "/vonga/images/categories/kimonos/flora/flora-04-blush.webp", description: "A blush floral duster with sculptural puff sleeves, layered over a tonal co-ord.", details: ["Sculptural puff sleeve", "Tonal sash belt", "Matching co-ord beneath"], sizes: ["S","M","L","XL","2XL"], colours: ["Blush Pink"], style: "kimonos", subStyle: "flora" },

  // Vonga Kimonos — Dress Kimono (one-piece kimono-collar dress)
  { id: "coral-bloom-kimono-dress", name: "Coral Bloom Kimono Dress", category: "Kimono", price: 2900, image: "/vonga/images/categories/kimonos/dress/dress-01-coral.webp", description: "A relaxed kimono-collar dress in a coral floral print, finished with kimono sleeves.", details: ["Kimono collar", "Wide kimono sleeve", "Relaxed silhouette"], sizes: ["S","M","L","XL","2XL"], colours: ["Coral"], style: "kimonos", subStyle: "dress" },
  { id: "meadow-print-kimono-dress", name: "Meadow Print Kimono Dress", category: "Kimono", price: 2900, image: "/vonga/images/categories/kimonos/dress/dress-02-meadow.webp", description: "A tie-dye meadow print kimono dress with a drawstring waist for a flattering shape.", details: ["Tie-dye floral print", "Drawstring waist", "Kimono collar"], sizes: ["S","M","L","XL","2XL"], colours: ["Meadow Multi"], style: "kimonos", subStyle: "dress" },
  { id: "rose-petal-kimono-dress", name: "Rose Petal Kimono Dress", category: "Kimono", price: 3000, image: "/vonga/images/categories/kimonos/dress/dress-03-rose.webp", description: "A rose-print kimono dress with sculptural shoulders and a cinched waist tie.", details: ["Sculptural shoulder", "Cinched waist tie", "Kimono collar"], sizes: ["S","M","L","XL","2XL"], colours: ["Rose Pink"], style: "kimonos", subStyle: "dress" },
  { id: "bronze-vine-kimono-dress", name: "Bronze Vine Kimono Dress", category: "Kimono", price: 3200, image: "/vonga/images/categories/kimonos/dress/dress-04-bronze.webp", description: "A bronze vine-print kimono dress in fluid jacquard, finished with a front slit.", details: ["Bronze jacquard print", "Front slit", "Kimono collar"], sizes: ["S","M","L","XL","2XL"], colours: ["Bronze"], style: "kimonos", subStyle: "dress" },

  // Vonga Corporate
  { id: "charcoal-power-blazer-set", name: "Charcoal Power Blazer Set", category: "Tailoring", price: 3400, image: "/vonga/images/categories/corporate-style/corporate-style-01.webp", description: "A tailored charcoal blazer and trouser set built for the boardroom.", details: ["Structured shoulder", "Matching tailored trouser", "Fully lined"], sizes: ["XS","S","M","L","XL"], colours: ["Charcoal"], style: "corporate-style" },
  { id: "ivory-tailored-trouser-suit", name: "Ivory Tailored Trouser Suit", category: "Tailoring", price: 3600, image: "/vonga/images/categories/corporate-style/corporate-style-02.webp", description: "A crisp ivory trouser suit with a sculpted waist for polished command dressing.", details: ["Sculpted waist", "Straight-leg trouser", "Sharp lapel"], sizes: ["XS","S","M","L","XL"], colours: ["Ivory"], style: "corporate-style" },
  { id: "slate-pinstripe-blazer-suit", name: "Slate Pinstripe Blazer Suit", category: "Tailoring", price: 3900, image: "/vonga/images/lookbook/look-4.webp", description: "A double-breasted pinstripe blazer suit in slate grey, cut for sharp, boardroom-ready authority.", details: ["Double-breasted lapel", "Pinstripe weave", "Tailored trouser"], sizes: ["XS","S","M","L","XL"], colours: ["Slate Grey"], style: "corporate-style" },

  // Vonga Jump Suits
  { id: "navy-satin-jumpsuit-set", name: "Navy Satin Jumpsuit Set", category: "Occasionwear", price: 3400, image: "/vonga/images/products/navy-satin-jumpsuit-set.webp", description: "A rich navy satin two-piece with a boat-neck top and tapered, pocketed trouser.", details: ["Boat neckline", "Tapered pocketed trouser", "Lustrous satin finish"], sizes: ["XS","S","M","L","XL"], colours: ["Navy"], style: "jump-suits" },
  { id: "mauve-satin-jumpsuit-set", name: "Mauve Satin Jumpsuit Set", category: "Occasionwear", price: 3400, image: "/vonga/images/products/mauve-satin-jumpsuit-set.webp", description: "A soft mauve satin two-piece with a boat-neck top and flared, pleated trouser.", details: ["Boat neckline", "Pleated flared trouser", "Lustrous satin finish"], sizes: ["XS","S","M","L","XL"], colours: ["Mauve"], style: "jump-suits" },
  { id: "royal-blue-satin-jumpsuit-set", name: "Royal Blue Satin Jumpsuit Set", category: "Occasionwear", price: 3400, image: "/vonga/images/products/royal-blue-satin-jumpsuit-set.webp", description: "A vivid royal blue satin two-piece with a V-neck top and sleek straight-leg trouser.", details: ["V-neckline", "Sleek straight-leg trouser", "Lustrous satin finish"], sizes: ["XS","S","M","L","XL"], colours: ["Royal Blue"], style: "jump-suits" },

  // Vonga Classy Blacks
  { id: "noir-slip-mini-dress", name: "Noir Slip Mini Dress", category: "Occasionwear", price: 2600, image: "/vonga/images/products/noir-slip-mini-dress.webp", description: "A clean-lined satin slip mini with a plunging V-neckline for effortless evening polish.", details: ["Plunging V-neckline", "Fitted slip silhouette", "Lace-trimmed hem"], sizes: ["XS","S","M","L","XL"], colours: ["Noir"], style: "classy-black" },
  { id: "noir-draped-slit-gown", name: "Noir Draped Slit Gown", category: "Occasionwear", price: 4500, image: "/vonga/images/products/noir-draped-slit-gown.webp", description: "A draped one-shoulder sequin gown with a sculpted waistband and a dramatic thigh-high slit.", details: ["Draped one-shoulder bodice", "Sequin column skirt", "Thigh-high slit"], sizes: ["S","M","L","XL","2XL"], colours: ["Noir"], style: "classy-black" },
  { id: "noir-lace-tulle-slit-gown", name: "Noir Lace Tulle Slit Gown", category: "Occasionwear", price: 4700, image: "/vonga/images/products/noir-lace-tulle-slit-gown.webp", description: "An illusion lace bodice flowing into a sweeping tulle skirt with a high slit.", details: ["Illusion lace bodice", "Sweeping tulle skirt", "High front slit"], sizes: ["S","M","L","XL"], colours: ["Noir"], style: "classy-black" },
  { id: "noir-sculptural-bow-gown", name: "Noir Sculptural Bow Gown", category: "Occasionwear", price: 4400, image: "/vonga/images/products/noir-sculptural-bow-gown.webp", description: "A sleek satin column gown with a sculptural oversized bow at one shoulder.", details: ["Sculptural bow shoulder", "Keyhole bodice cutout", "Column silhouette"], sizes: ["S","M","L","XL"], colours: ["Noir"], style: "classy-black" },

  // Vonga Traditional
  { id: "orange-puff-sleeve-ankara-dress", name: "Orange Puff Sleeve Ankara Dress", category: "Traditional Wear", price: 2800, image: "/vonga/images/categories/traditional-chic/traditional-chic-orange-puff-ankara.webp", description: "A statement Ankara print dress with voluminous satin puff sleeves and a corseted bodice.", details: ["Voluminous satin puff sleeves", "Corseted bodice", "Authentic Ankara print"], sizes: ["XS","S","M","L","XL"], colours: ["Orange Multi"], style: "traditional-chic", subStyle: "signature" },
  { id: "noir-floral-wrap-gown", name: "Noir Floral Wrap Gown", category: "Traditional Wear", price: 4200, image: "/vonga/images/categories/traditional-chic/traditional-chic-noir-floral-wrap-gown.webp", description: "A one-shoulder floral sequin gown with a draped wrap skirt for elevated occasions.", details: ["One-shoulder draped bodice", "Floral sequin embroidery", "Wrapped skirt silhouette"], sizes: ["S","M","L","XL","2XL"], colours: ["Noir Floral"], style: "traditional-chic", subStyle: "signature" },
  { id: "emerald-beaded-ankara-gown", name: "Emerald Beaded Ankara Gown", category: "Traditional Wear", price: 3600, image: "/vonga/images/categories/traditional-chic/traditional-chic-emerald-beaded-ankara.webp", description: "An off-shoulder satin bodice beaded at the waist, paired with a fitted Ankara print skirt.", details: ["Beaded off-shoulder bodice", "Puff sleeve detail", "Fitted Ankara print skirt"], sizes: ["S","M","L","XL"], colours: ["Emerald Multi"], style: "traditional-chic", subStyle: "signature" },
  { id: "slate-ankara-gele-set", name: "Slate Ankara Gele Set", category: "Traditional Wear", price: 3300, image: "/vonga/images/categories/traditional-chic/traditional-chic-slate-ankara-gele-set.webp", description: "A fitted off-shoulder Ankara gown with matching gele headwrap for a coordinated statement look.", details: ["Fitted off-shoulder silhouette", "Matching gele headwrap", "Waist sash detail"], sizes: ["XS","S","M","L","XL"], colours: ["Slate Blue"], style: "traditional-chic", subStyle: "signature" },

  // Vonga Traditional — Matching Couple
  { id: "couple-monochrome-tunic-set", name: "Monochrome Tunic Couple Set", category: "Traditional Wear", price: 5200, image: "/vonga/images/categories/traditional-chic/traditional-chic-couple-monochrome-tunic.webp", description: "A coordinated his-and-hers look pairing a striped monochrome tunic with a tailored little black dress.", details: ["Striped monochrome tunic", "Coordinated black dress", "Ready-to-wear pair"], sizes: ["S","M","L","XL"], colours: ["Black / White"], style: "traditional-chic", subStyle: "couples" },
  { id: "couple-cream-ankara-set", name: "Cream Ankara Couple Set", category: "Traditional Wear", price: 5400, image: "/vonga/images/categories/traditional-chic/traditional-chic-couple-cream-ankara.webp", description: "A coordinated cream and Ankara-panelled look with a cutout mini dress and matching tailored shirt.", details: ["Ankara panel detailing", "Cutout mini dress", "Matching tailored shirt"], sizes: ["S","M","L","XL"], colours: ["Cream Multi"], style: "traditional-chic", subStyle: "couples" },
  { id: "couple-crimson-ankara-set", name: "Crimson Ankara Couple Set", category: "Traditional Wear", price: 5000, image: "/vonga/images/categories/traditional-chic/traditional-chic-couple-crimson-ankara.webp", description: "A coordinated crimson Ankara print look with a ruffle-sleeve dress and matching relaxed trouser set.", details: ["Ruffle shoulder detail", "Matching Ankara print pair", "Relaxed trouser fit"], sizes: ["S","M","L","XL"], colours: ["Crimson Multi"], style: "traditional-chic", subStyle: "couples" },
  { id: "couple-chartreuse-ankara-set", name: "Chartreuse Ankara Couple Set", category: "Traditional Wear", price: 5100, image: "/vonga/images/categories/traditional-chic/traditional-chic-couple-chartreuse-ankara.webp", description: "A coordinated chartreuse check Ankara look with an off-shoulder gown and matching button-up shirt.", details: ["Off-shoulder sheer sleeve gown", "Matching check Ankara shirt", "Coordinated print pair"], sizes: ["S","M","L","XL"], colours: ["Chartreuse Multi"], style: "traditional-chic", subStyle: "couples" },
];

export const formatRand = (value: number) => `R${value.toLocaleString("en-ZA")}`;

export type VongaCategoryStyle = { slug: string; name: string; description: string; count: number };

export const vongaCategoryStyles: VongaCategoryStyle[] = [
  { slug: "chic-gems", name: "Chic Gems", description: "Sequins, sparkle and jewel tones for entrances that get remembered.", count: 12 },
  { slug: "brides", name: "Bridals", description: "Sculpted white and ivory silhouettes for the aisle and beyond.", count: 2 },
  { slug: "kimonos", name: "Kimonos", description: "Statement duster jackets in bold print and drape.", count: 6 },
  { slug: "corporate-style", name: "Corporate", description: "Sharp tailoring for the boardroom and beyond.", count: 14 },
  { slug: "jump-suits", name: "Jump Suits", description: "One-piece silhouettes with sculptural drape and movement.", count: 3 },
  { slug: "classy-black", name: "Classy Blacks", description: "Sequined and sculpted black-tie evening wear.", count: 15 },
  { slug: "traditional-chic", name: "Traditional", description: "Ankara print and cultural craft, reimagined for modern occasions.", count: 15 },
];

export const vongaCategoryImages = (slug: string, count: number) =>
  Array.from({ length: count }, (_, index) => `/vonga/images/categories/${slug}/${slug}-${String(index + 1).padStart(2, "0")}.jpg`);
