export type VongaProduct = {
  id: string;
  name: string;
  category: string;
  price: number;
  image: string;
  description: string;
  details: string[];
  sizes: string[];
  colours: string[];
  featured?: boolean;
  style?: string;
  subStyle?: string;
};

export const vongaProducts: VongaProduct[] = [
  { id: "ivory-pleated-pocket-dress", featured: true, name: "Ivory Pleated Pocket Dress", category: "Occasionwear", price: 2600, image: "/vonga/images/products/ivory-pleated-pocket-dress.png", description: "A draped ivory mini with a plunging pleated bodice and structured hip pockets.", details: ["Pleated V-neckline", "Structured hip pockets", "Made in Pretoria"], sizes: ["XS","S","M","L","XL"], colours: ["Ivory"] },
  { id: "sunset-bloom-kimono-set", featured: true, name: "Sunset Bloom Kimono Set", category: "Occasionwear", price: 4600, image: "/vonga/images/products/sunset-bloom-kimono-set.png", description: "An oversized floral jacquard duster layered over a matching tailored set.", details: ["Jacquard floral duster", "Matching wide-leg trousers", "Statement sleeve"], sizes: ["XS","S","M","L","XL"], colours: ["Sunset Orange"] },
  { id: "scarlet-bloom-mermaid-skirt", featured: true, name: "Scarlet Bloom Mermaid Skirt", category: "Occasionwear", price: 3800, image: "/vonga/images/products/scarlet-bloom-mermaid-skirt.png", description: "A velvet puff-sleeve bodice paired with a sculpted floral mermaid skirt.", details: ["Velvet puff sleeve", "Floral satin mermaid skirt", "Atelier finishing"], sizes: ["S","M","L","XL"], colours: ["Noir / Scarlet"] },
  { id: "midnight-cross-gown", featured: true, name: "Midnight Cross Gown", category: "Occasionwear", price: 4200, image: "/vonga/images/products/midnight-cross-gown.png", description: "A cross-front cutout bodice flowing into a sculpted midnight mermaid gown.", details: ["Cross-front cutout bodice", "Sculpted mermaid silhouette", "Fully lined"], sizes: ["S","M","L","XL"], colours: ["Midnight Navy"] },
  { id: "scarlet-rose-shoulder-gown", name: "Scarlet Rose Shoulder Gown", category: "Occasionwear", price: 3950, image: "/vonga/images/products/scarlet-rose-shoulder-gown.png", description: "A dramatic scarlet gown crowned with a sculpted 3D rose shoulder embellishment.", details: ["Hand-appliquéd 3D rose petals", "Sculpted shoulder statement", "Fitted bodice"], sizes: ["XS","S","M","L","XL"], colours: ["Scarlet"] },
  { id: "midnight-medallion-blazer", name: "Midnight Medallion Blazer", category: "Tailoring", price: 3650, image: "/vonga/images/womenswear/womenswear-1.jpg", description: "A sharply sculpted blazer dress punctuated with gilded medallion details.", details: ["Structured shoulder", "Double-breasted closure", "Sculpted waist"], sizes: ["XS","S","M","L","XL"], colours: ["Black / Gold"], style: "corporate-style" },
  { id: "scarlet-command-suit", name: "Scarlet Command Suit", category: "Tailoring", price: 4200, image: "/vonga/images/womenswear/womenswear-2.jpg", description: "Off-shoulder scarlet tailoring with a fluid wide-leg trouser.", details: ["Architectural neckline", "Wide-leg cut", "Two-piece set"], sizes: ["XS","S","M","L","XL"], colours: ["Scarlet"], style: "corporate-style" },
  { id: "scarlet-bloom-mini", name: "Scarlet Bloom Mini", category: "Dresses", price: 2950, image: "/vonga/images/womenswear/womenswear-3.jpg", description: "A playful couture mini shaped with a champagne bloom and sculptural volume.", details: ["Hand-shaped floral appliqué", "Layered tulle skirt", "Corseted bodice"], sizes: ["XS","S","M","L"], colours: ["Scarlet / Champagne"] },
  { id: "fuchsia-rose-couture", name: "Fuchsia Rose Couture", category: "Dresses", price: 4800, image: "/vonga/images/womenswear/womenswear-4.jpg", description: "Embroidered corsetry meets dimensional satin roses in vivid fuchsia.", details: ["Embellished corset", "Hand-applied satin roses", "Statement shoulder"], sizes: ["S","M","L","XL"], colours: ["Fuchsia"] },
  { id: "noir-rose-corset", name: "Noir Rose Corset", category: "Occasionwear", price: 3300, image: "/vonga/images/womenswear/womenswear-5.jpg", description: "A dramatic rose-sculpted corset for evening dressing with impact.", details: ["Satin rose construction", "Boned inner corset", "Atelier finish"], sizes: ["XS","S","M","L","XL"], colours: ["Noir"] },
  { id: "lagoon-bow-jumpsuit", name: "Lagoon Bow Jumpsuit", category: "Occasionwear", price: 3900, image: "/vonga/images/occasion/occasion-1.jpg", description: "A jewel-toned jumpsuit with an oversized bow and crystal embroidery.", details: ["Asymmetric statement bow", "Crystal embellishment", "Floor-sweeping overskirt"], sizes: ["S","M","L","XL","2XL"], colours: ["Lagoon"], style: "jump-suits" },
  { id: "crimson-rose-ballgown", name: "Crimson Rose Ballgown", category: "Occasionwear", price: 5200, image: "/vonga/images/occasion/occasion-2.jpg", description: "A romantic floral ballgown balanced by a dramatic high-low silhouette.", details: ["Structured strapless bodice", "High-low skirt", "Printed satin"], sizes: ["S","M","L","XL","2XL"], colours: ["Crimson Rose"] },
  { id: "amethyst-ruffle-mini", name: "Amethyst Ruffle Mini", category: "Dresses", price: 2750, image: "/vonga/images/occasion/occasion-3.jpg", description: "A buoyant amethyst mini with weightless tiers and a defined waist.", details: ["Layered organza ruffles", "Soft flutter sleeve", "Fitted waistband"], sizes: ["XS","S","M","L","XL"], colours: ["Amethyst"] },

  // Vonga Chic Gems
  { id: "scarlet-peplum-mini-dress", name: "Scarlet Peplum Mini Dress", category: "Dresses", price: 3200, image: "/vonga/images/categories/chic-gems/looks/gems-01-scarlet-peplum.png", description: "A sculpted scarlet satin mini finished with a structured peplum waist.", details: ["Structured peplum waist", "Cap sleeve", "Fitted silhouette"], sizes: ["XS","S","M","L","XL"], colours: ["Scarlet"], style: "chic-gems" },
  { id: "pearl-cutout-mini-dress", name: "Pearl Cutout Mini Dress", category: "Dresses", price: 3600, image: "/vonga/images/categories/chic-gems/looks/gems-02-pearl-cutout.png", description: "A fully beaded ivory mini with a cutout bodice, lace sleeves and a sweeping train.", details: ["Hand-beaded pearl finish", "Cutout bodice", "Sweeping detachable train"], sizes: ["S","M","L","XL","2XL"], colours: ["Ivory"], style: "chic-gems" },
  { id: "champagne-cape-mini-dress", name: "Champagne Cape Mini Dress", category: "Dresses", price: 3400, image: "/vonga/images/categories/chic-gems/looks/gems-03-champagne-cape.png", description: "A one-shoulder champagne mini with a sequined bodice and a sweeping cape sleeve.", details: ["One-shoulder cape sleeve", "Sequined bodice", "Bow waist detail"], sizes: ["XS","S","M","L"], colours: ["Champagne"], style: "chic-gems" },
  { id: "ivory-sequin-column-dress", name: "Ivory Sequin Column Dress", category: "Occasionwear", price: 3900, image: "/vonga/images/categories/chic-gems/looks/gems-04-ivory-sequin-coat.png", description: "A structured ivory column dress with a sequined bodice, sculpted peplum and thigh-high slit.", details: ["Sequined structured bodice", "Sculpted peplum sleeve", "Thigh-high slit"], sizes: ["XS","S","M","L","XL"], colours: ["Ivory"], style: "chic-gems" },

  // Vonga Bridals
  { id: "ivory-sculpted-bridal-gown", name: "Ivory Sculpted Bridal Gown", category: "Bridal", price: 8900, image: "/vonga/images/categories/brides/brides-01.jpg", description: "A sculpted ivory gown with a fitted corset bodice and a cathedral-length train.", details: ["Boned corset bodice", "Cathedral train", "Hand-finished ivory silk"], sizes: ["XS","S","M","L","XL"], colours: ["Ivory"], style: "brides" },
  { id: "lace-whisper-bridal-gown", name: "Lace Whisper Bridal Gown", category: "Bridal", price: 7600, image: "/vonga/images/categories/brides/brides-02.jpg", description: "Delicate lace appliqué over a soft tulle skirt for a romantic aisle moment.", details: ["Hand-appliquéd lace", "Layered tulle skirt", "Illusion back"], sizes: ["S","M","L","XL"], colours: ["Ivory"], style: "brides" },
  { id: "pearl-trail-wedding-gown", name: "Pearl Trail Wedding Gown", category: "Bridal", price: 9400, image: "/vonga/images/categories/brides/brides-01.jpg", description: "A pearl-embellished bodice flowing into a sculpted mermaid silhouette.", details: ["Pearl-embellished bodice", "Sculpted mermaid skirt", "Detachable overskirt"], sizes: ["S","M","L","XL"], colours: ["Ivory / Pearl"], style: "brides" },
  { id: "silk-veil-bridal-gown", name: "Silk Veil Bridal Gown", category: "Bridal", price: 8200, image: "/vonga/images/categories/brides/brides-02.jpg", description: "Fluid silk crepe with a draped neckline for understated bridal elegance.", details: ["Draped silk crepe", "Softly gathered waist", "Chapel-length train"], sizes: ["XS","S","M","L","XL"], colours: ["Ivory"], style: "brides" },

  // Vonga Kimonos — Flora Kimonos (belted floral duster + co-ord)
  { id: "emerald-garden-kimono-robe", name: "Emerald Garden Kimono Robe", category: "Kimono", price: 3600, image: "/vonga/images/categories/kimonos/flora/flora-01-emerald.png", description: "An emerald floral duster with balloon sleeves, sashed over a matching co-ord.", details: ["Oversized floral duster", "Balloon sleeve", "Matching sash belt"], sizes: ["S","M","L","XL","2XL"], colours: ["Emerald Green"], style: "kimonos", subStyle: "flora" },
  { id: "lilac-mist-kimono-robe", name: "Lilac Mist Kimono Robe", category: "Kimono", price: 3600, image: "/vonga/images/categories/kimonos/flora/flora-02-lilac.png", description: "A soft floral duster in lilac tones with dramatic bubble sleeves and a tie waist.", details: ["Dramatic bubble sleeve", "Self-tie waist sash", "Fluid floral drape"], sizes: ["S","M","L","XL","2XL"], colours: ["Lilac"], style: "kimonos", subStyle: "flora" },
  { id: "ocean-bloom-kimono-robe", name: "Ocean Bloom Kimono Robe", category: "Kimono", price: 3800, image: "/vonga/images/categories/kimonos/flora/flora-03-ocean.png", description: "A watercolour floral duster in ocean blues and greens, sashed at the waist.", details: ["Watercolour floral print", "Balloon sleeve", "Emerald sash belt"], sizes: ["S","M","L","XL","2XL"], colours: ["Ocean Blue/Green"], style: "kimonos", subStyle: "flora" },
  { id: "blush-bloom-kimono-robe", name: "Blush Bloom Kimono Robe", category: "Kimono", price: 3600, image: "/vonga/images/categories/kimonos/flora/flora-04-blush.png", description: "A blush floral duster with sculptural puff sleeves, layered over a tonal co-ord.", details: ["Sculptural puff sleeve", "Tonal sash belt", "Matching co-ord beneath"], sizes: ["S","M","L","XL","2XL"], colours: ["Blush Pink"], style: "kimonos", subStyle: "flora" },

  // Vonga Kimonos — Dress Kimono (one-piece kimono-collar dress)
  { id: "coral-bloom-kimono-dress", name: "Coral Bloom Kimono Dress", category: "Kimono", price: 2900, image: "/vonga/images/categories/kimonos/dress/dress-01-coral.png", description: "A relaxed kimono-collar dress in a coral floral print, finished with kimono sleeves.", details: ["Kimono collar", "Wide kimono sleeve", "Relaxed silhouette"], sizes: ["S","M","L","XL","2XL"], colours: ["Coral"], style: "kimonos", subStyle: "dress" },
  { id: "meadow-print-kimono-dress", name: "Meadow Print Kimono Dress", category: "Kimono", price: 2900, image: "/vonga/images/categories/kimonos/dress/dress-02-meadow.png", description: "A tie-dye meadow print kimono dress with a drawstring waist for a flattering shape.", details: ["Tie-dye floral print", "Drawstring waist", "Kimono collar"], sizes: ["S","M","L","XL","2XL"], colours: ["Meadow Multi"], style: "kimonos", subStyle: "dress" },
  { id: "rose-petal-kimono-dress", name: "Rose Petal Kimono Dress", category: "Kimono", price: 3000, image: "/vonga/images/categories/kimonos/dress/dress-03-rose.png", description: "A rose-print kimono dress with sculptural shoulders and a cinched waist tie.", details: ["Sculptural shoulder", "Cinched waist tie", "Kimono collar"], sizes: ["S","M","L","XL","2XL"], colours: ["Rose Pink"], style: "kimonos", subStyle: "dress" },
  { id: "bronze-vine-kimono-dress", name: "Bronze Vine Kimono Dress", category: "Kimono", price: 3200, image: "/vonga/images/categories/kimonos/dress/dress-04-bronze.png", description: "A bronze vine-print kimono dress in fluid jacquard, finished with a front slit.", details: ["Bronze jacquard print", "Front slit", "Kimono collar"], sizes: ["S","M","L","XL","2XL"], colours: ["Bronze"], style: "kimonos", subStyle: "dress" },

  // Vonga Corporate
  { id: "charcoal-power-blazer-set", name: "Charcoal Power Blazer Set", category: "Tailoring", price: 3400, image: "/vonga/images/categories/corporate-style/corporate-style-01.jpg", description: "A tailored charcoal blazer and trouser set built for the boardroom.", details: ["Structured shoulder", "Matching tailored trouser", "Fully lined"], sizes: ["XS","S","M","L","XL"], colours: ["Charcoal"], style: "corporate-style" },
  { id: "ivory-tailored-trouser-suit", name: "Ivory Tailored Trouser Suit", category: "Tailoring", price: 3600, image: "/vonga/images/categories/corporate-style/corporate-style-02.jpg", description: "A crisp ivory trouser suit with a sculpted waist for polished command dressing.", details: ["Sculpted waist", "Straight-leg trouser", "Sharp lapel"], sizes: ["XS","S","M","L","XL"], colours: ["Ivory"], style: "corporate-style" },

  // Vonga Jump Suits
  { id: "onyx-tailored-jumpsuit", name: "Onyx Tailored Jumpsuit", category: "Occasionwear", price: 3200, image: "/vonga/images/categories/jump-suits/jump-suits-01.jpg", description: "A sharply tailored onyx jumpsuit with a cinched waist and wide leg.", details: ["Cinched waist", "Wide-leg cut", "Concealed zip"], sizes: ["XS","S","M","L","XL"], colours: ["Onyx"], style: "jump-suits" },
  { id: "emerald-wrap-jumpsuit", name: "Emerald Wrap Jumpsuit", category: "Occasionwear", price: 3050, image: "/vonga/images/categories/jump-suits/jump-suits-02.jpg", description: "A wrap-front jumpsuit in emerald crepe with a fluid, sculpted drape.", details: ["Wrap-front bodice", "Fluid crepe drape", "Self-tie waist"], sizes: ["S","M","L","XL"], colours: ["Emerald"], style: "jump-suits" },
  { id: "sandstone-culotte-jumpsuit", name: "Sandstone Culotte Jumpsuit", category: "Occasionwear", price: 2900, image: "/vonga/images/categories/jump-suits/jump-suits-03.jpg", description: "A relaxed culotte jumpsuit in sandstone with a structured bodice.", details: ["Structured bodice", "Culotte leg", "Belted waist"], sizes: ["XS","S","M","L","XL"], colours: ["Sandstone"], style: "jump-suits" },

  // Vonga Classy Blacks
  { id: "noir-sequin-halter-gown", name: "Noir Sequin Halter Gown", category: "Occasionwear", price: 4600, image: "/vonga/images/categories/classy-black/looks/black-01-sequin-halter.png", description: "A fully sequined halter gown with a plunging neckline and a sculpted mermaid skirt.", details: ["Plunging halter neckline", "Fully sequined finish", "Sculpted mermaid skirt"], sizes: ["XS","S","M","L","XL"], colours: ["Noir"], style: "classy-black" },
  { id: "noir-feather-slit-gown", name: "Noir Feather Slit Gown", category: "Occasionwear", price: 4200, image: "/vonga/images/categories/classy-black/looks/black-02-feather-slit.png", description: "An off-shoulder gown finished with feather trim and a dramatic thigh-high slit.", details: ["Feather-trimmed neckline", "Off-shoulder silhouette", "Thigh-high slit"], sizes: ["S","M","L","XL","2XL"], colours: ["Noir"], style: "classy-black" },
  { id: "noir-sequin-skirt-set", name: "Noir Sequin Skirt Set", category: "Occasionwear", price: 3900, image: "/vonga/images/categories/classy-black/looks/black-03-sequin-skirt.png", description: "An off-shoulder puff-sleeve top paired with a fully sequined column skirt.", details: ["Sheer puff sleeve", "Off-shoulder neckline", "Sequined column skirt"], sizes: ["S","M","L","XL","2XL"], colours: ["Noir"], style: "classy-black" },
  { id: "noir-cape-gown", name: "Noir Cape Gown", category: "Occasionwear", price: 4400, image: "/vonga/images/categories/classy-black/looks/black-04-cape-gown.png", description: "A one-shoulder gown with a sweeping cape sleeve and beaded peplum waist.", details: ["Sweeping cape sleeve", "Beaded peplum waist", "Column skirt"], sizes: ["S","M","L","XL"], colours: ["Noir"], style: "classy-black" },

  // Vonga Traditional
  { id: "ankara-wrap-dress", name: "Ankara Wrap Dress", category: "Traditional Wear", price: 2500, image: "/vonga/images/categories/traditional-chic/traditional-chic-01.jpg", description: "A vibrant Ankara print wrap dress cut for a flattering, fluid silhouette.", details: ["Authentic Ankara print", "Wrap-front tie", "Fitted waist"], sizes: ["XS","S","M","L","XL"], colours: ["Multi Print"], style: "traditional-chic" },
  { id: "heritage-print-gown", name: "Heritage Print Gown", category: "Traditional Wear", price: 3100, image: "/vonga/images/categories/traditional-chic/traditional-chic-02.jpg", description: "A floor-length heritage-print gown finished with a sculpted waistband.", details: ["Bold heritage print", "Sculpted waistband", "Floor-length hem"], sizes: ["S","M","L","XL"], colours: ["Multi Print"], style: "traditional-chic" },
  { id: "kente-trim-two-piece", name: "Kente-Trim Two Piece", category: "Traditional Wear", price: 2950, image: "/vonga/images/categories/traditional-chic/traditional-chic-03.jpg", description: "A modern two-piece set trimmed in kente-inspired detailing.", details: ["Kente-inspired trim", "Crop top and skirt set", "Hand-finished edges"], sizes: ["XS","S","M","L","XL"], colours: ["Multi Print / Gold"], style: "traditional-chic" },
  { id: "royal-print-boubou-dress", name: "Royal Print Boubou Dress", category: "Traditional Wear", price: 2700, image: "/vonga/images/categories/traditional-chic/traditional-chic-04.jpg", description: "A relaxed boubou silhouette in a rich traditional print, finished with hand embroidery.", details: ["Rich traditional print", "Hand embroidery detail", "Relaxed boubou fit"], sizes: ["XS","S","M","L","XL"], colours: ["Royal Print"], style: "traditional-chic" },
];

export const formatRand = (value: number) => `R${value.toLocaleString("en-ZA")}`;

export type VongaCategoryStyle = { slug: string; name: string; description: string; count: number };

export const vongaCategoryStyles: VongaCategoryStyle[] = [
  { slug: "chic-gems", name: "Chic Gems", description: "Sequins, sparkle and jewel tones for entrances that get remembered.", count: 12 },
  { slug: "brides", name: "Bridals", description: "Sculpted white and ivory silhouettes for the aisle and beyond.", count: 2 },
  { slug: "kimonos", name: "Kimonos", description: "Statement duster jackets in bold print and drape.", count: 6 },
  { slug: "corporate-style", name: "Corporate", description: "Sharp tailoring for the boardroom and beyond.", count: 14 },
  { slug: "jump-suits", name: "Jump Suits", description: "One-piece silhouettes with sculptural drape and movement.", count: 3 },
  { slug: "classy-black", name: "Classy Blacks", description: "Sequined and sculpted black-tie evening wear.", count: 15 },
  { slug: "traditional-chic", name: "Traditional", description: "Ankara print and cultural craft, reimagined for modern occasions.", count: 15 },
];

export const vongaCategoryImages = (slug: string, count: number) =>
  Array.from({ length: count }, (_, index) => `/vonga/images/categories/${slug}/${slug}-${String(index + 1).padStart(2, "0")}.jpg`);
